### ISSUE TITLE
Search bar placeholder text styles are not being applied correctly in Chrome OSX and Firefox

### ISSUE THREAD

**Issue by cheics-d2l** [BrightspaceUI/inputs#69]
**Expected design:**
![image](https://user-images.githubusercontent.com/8430763/52489211-ac260000-2b8f-11e9-94c4-eea824d2086c.png)
The search input placeholder should be is supposed to be:
- [Mica](http://design.d2l/style/colour/) #D3D9E3 
- Regular weight text

The styles seem to not be applied correctly in either Chrome or Firefox. (Confirmed using the input demo page in the repo).

**Chrome OSX:**
![image](https://user-images.githubusercontent.com/8430763/52489264-ccee5580-2b8f-11e9-89b1-e5a030fc35d9.png)
- Text is bold
- (looks pretty close to the right colour)

**Firefox OSX:**
![image](https://user-images.githubusercontent.com/8430763/52489331-fad39a00-2b8f-11e9-9b90-7da5fabe6045.png)
- Text is right weight (I think, might be Light)
- Text is REALLY hard to see - much lighter than Mica

**Comment by dlockhart** [comment]
@cheics-d2l I can confirm that the placeholder colour [is being set to Mica](https://github.com/BrightspaceUI/inputs/blob/master/d2l-input-shared-styles.js#L19).

The font weight [is 400 (normal)](https://github.com/BrightspaceUI/inputs/blob/master/d2l-input-shared-styles.js#L69), not bold. You can test that by typing the same placeholder text overtop of it (e.g. "Search for some stuff" and then quickly remove and add it -- nothing jitters because the placeholder and non-placeholder have the same weight.

![input-placeholder](https://user-images.githubusercontent.com/5491151/52508888-1bb5e280-2bc4-11e9-9267-4f5855df5307.gif)

You're correct that Firefox is doing something weird though. I tracked it down to Firefox having a default placeholder opacity of something other than `1`. If I set `opacity: 1` then it looks the same as Chrome -- will fix.
